In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os.path as osp
import sys

RESULTS_DIR = osp.join('../', 'results')

py_results = pd.read_csv(osp.join(RESULTS_DIR, 'bench_io_py.csv'))
cpp_results = pd.read_csv(osp.join(RESULTS_DIR, 'bench_io_cpp.csv'))

In [21]:
py_results

,host,function,duration_formatted(us),M,N
0,zaddle-Ubuntu-Satus,test_encode_1cNxN,111.6220,NaN,128
1,zaddle-Ubuntu-Satus,test_encode_1cNxN,95.5837,NaN,256
2,zaddle-Ubuntu-Satus,test_encode_1cNxN,165.8910,NaN,512
3,zaddle-Ubuntu-Satus,test_encode_1cNxN,536.4820,NaN,1024
4,zaddle-Ubuntu-Satus,test_encode_1cNxN,2186.2310,NaN,2048
5,zaddle-Ubuntu-Satus,test_encode_1cNxN,8007.3857,NaN,4096
6,zaddle-Ubuntu-Satus,test_encode_1cNxN,31137.5857,NaN,8192
7,zaddle-Ubuntu-Satus,test_decode_1cNxN,11.9398,NaN,128
8,zaddle-Ubuntu-Satus,test_decode_1cNxN,30.2964,NaN,256
9,zaddle-Ubuntu-Satus,test_decode_1cNxN,106.1074,NaN,512
10,zaddle-Ubuntu-Satus,test_decode_1cNxN,427.4963,NaN,1024
11,zaddle-Ubuntu-Satus,test_decode_1cNxN,1687.3446,NaN,2048
12,zaddle-Ubuntu-Satus,test_decode_1cNxN,12263.0737,NaN,4096
13,zaddle-Ubuntu-Satus,test_decode_1cNxN,50444.1808,NaN,8192
14,zaddle-Ubuntu-Satus,test_encode_Nc4096x4096,10550.6043,NaN,1
15,zaddle-Ubuntu-Satus,test_encode_Nc4096x4096,24784.0937,NaN,3
16,zaddle-Ubuntu-Satus,test_encode_Nc4096x4096,33417.0733,NaN,4
17,zaddle-Ubuntu-Satus,test_decode_Nc4096x4096,12476.1909,NaN,1
18,zaddle-Ubuntu-Satus,test_decode_Nc4096x4096,27887.5218,NaN,3
19,zaddle-Ubuntu-Satus,test_decode_Nc4096x4096,34026.1617,NaN,4
20,zaddle-Ubuntu-Satus,test_encode_1cNxM,753.0603,4860.0,240
21,zaddle-Ubuntu-Satus,test_encode_1cNxM,611.9703,3240.0,360
22,zaddle-Ubuntu-Satus,test_encode_1cNxM,631.3613,2430.0,480
23,zaddle-Ubuntu-Satus,test_encode_1cNxM,600.9860,1620.0,720
24,zaddle-Ubuntu-Satus,test_encode_1cNxM,595.7723,1440.0,810
25,zaddle-Ubuntu-Satus,test_encode_1cNxM,595.8197,1080.0,1080
26,zaddle-Ubuntu-Satus,test_encode_1cNxM,600.0127,810.0,1440
27,zaddle-Ubuntu-Satus,test_encode_1cNxM,594.1383,720.0,1620
28,zaddle-Ubuntu-Satus,test_encode_1cNxM,631.3613,480.0,2430
29,zaddle-Ubuntu-Satus,test_encode_1cNxM,590.5723,360.0,3240
30,zaddle-Ubuntu-Satus,test_encode_1cNxM,584.5360,240.0,4860
31,zaddle-Ubuntu-Satus,test_decode_1cNxM,519.2513,4860.0,240
32,zaddle-Ubuntu-Satus,test_decode_1cNxM,503.7923,3240.0,360
33,zaddle-Ubuntu-Satus,test_decode_1cNxM,487.5178,2430.0,480
34,zaddle-Ubuntu-Satus,test_decode_1cNxM,480.4621,1620.0,720
35,zaddle-Ubuntu-Satus,test_decode_1cNxM,464.9759,1440.0,810
36,zaddle-Ubuntu-Satus,test_decode_1cNxM,467.0751,1080.0,1080
37,zaddle-Ubuntu-Satus,test_decode_1cNxM,448.3216,810.0,1440
38,zaddle-Ubuntu-Satus,test_decode_1cNxM,450.3138,720.0,1620
39,zaddle-Ubuntu-Satus,test_decode_1cNxM,423.7687,480.0,2430
40,zaddle-Ubuntu-Satus,test_decode_1cNxM,409.1829,360.0,3240
41,zaddle-Ubuntu-Satus,test_decode_1cNxM,402.0850,240.0,4860

In [22]:
cpp_results

,name,iterations,real_time,cpu_time,time_unit,bytes_per_second,items_per_second,label,error_occurred,error_message
0,encode_1cNxN/128,6165,0.237950,0.106559,ms,NaN,NaN,NaN,NaN,NaN
1,encode_1cNxN/256,2369,0.758894,0.384887,ms,NaN,NaN,NaN,NaN,NaN
2,encode_1cNxN/512,498,1.550790,1.405330,ms,NaN,NaN,NaN,NaN,NaN
3,encode_1cNxN/1024,129,5.585030,5.411690,ms,NaN,NaN,NaN,NaN,NaN
4,encode_1cNxN/2048,48,16.868500,16.300100,ms,NaN,NaN,NaN,NaN,NaN
5,encode_1cNxN/4096,14,53.188400,52.592000,ms,NaN,NaN,NaN,NaN,NaN
6,encode_1cNxN/8192,4,216.542000,196.351000,ms,NaN,NaN,NaN,NaN,NaN
7,decode_1cNxN/128,14547,0.047999,0.047998,ms,NaN,NaN,NaN,NaN,NaN
8,decode_1cNxN/256,3835,0.184079,0.184075,ms,NaN,NaN,NaN,NaN,NaN
9,decode_1cNxN/512,952,0.739492,0.739460,ms,NaN,NaN,NaN,NaN,NaN
10,decode_1cNxN/1024,232,2.973470,2.971350,ms,NaN,NaN,NaN,NaN,NaN
11,decode_1cNxN/2048,54,12.854600,12.852100,ms,NaN,NaN,NaN,NaN,NaN
12,decode_1cNxN/4096,10,70.825000,70.820200,ms,NaN,NaN,NaN,NaN,NaN
13,decode_1cNxN/8192,2,281.889000,281.879000,ms,NaN,NaN,NaN,NaN,NaN
14,encode_Nc4096x4096/1,14,53.984100,51.920400,ms,NaN,NaN,NaN,NaN,NaN
15,encode_Nc4096x4096/3,15,46.762500,46.156300,ms,NaN,NaN,NaN,NaN,NaN
16,encode_Nc4096x4096/4,11,65.234400,65.212800,ms,NaN,NaN,NaN,NaN,NaN
17,decode_Nc4096x4096/1,10,70.334800,70.333400,ms,NaN,NaN,NaN,NaN,NaN
18,decode_Nc4096x4096/3,9,73.395900,73.393000,ms,NaN,NaN,NaN,NaN,NaN
19,decode_Nc4096x4096/4,7,102.836000,102.830000,ms,NaN,NaN,NaN,NaN,NaN
20,encode_1cNxM/240/4860,121,5.575770,5.406150,ms,NaN,NaN,NaN,NaN,NaN
21,encode_1cNxM/360/3240,100,5.234350,5.113730,ms,NaN,NaN,NaN,NaN,NaN
22,encode_1cNxM/480/2430,153,5.851910,5.577230,ms,NaN,NaN,NaN,NaN,NaN
23,encode_1cNxM/720/1620,166,5.971730,5.770970,ms,NaN,NaN,NaN,NaN,NaN
24,encode_1cNxM/810/1440,115,6.154640,5.926680,ms,NaN,NaN,NaN,NaN,NaN
25,encode_1cNxM/1080/1080,114,5.417220,5.265150,ms,NaN,NaN,NaN,NaN,NaN
26,encode_1cNxM/1440/810,116,5.513130,5.255530,ms,NaN,NaN,NaN,NaN,NaN
27,encode_1cNxM/1620/720,116,5.015640,4.900250,ms,NaN,NaN,NaN,NaN,NaN
28,encode_1cNxM/2430/480,100,6.146000,5.922990,ms,NaN,NaN,NaN,NaN,NaN
29,encode_1cNxM/3240/360,115,5.031660,4.847250,ms,NaN,NaN,NaN,NaN,NaN
30,encode_1cNxM/4860/240,100,5.391060,5.172570,ms,NaN,NaN,NaN,NaN,NaN
31,decode_1cNxM/240/4860,216,3.257490,3.257440,ms,NaN,NaN,NaN,NaN,NaN
32,decode_1cNxM/360/3240,211,3.299300,3.299140,ms,NaN,NaN,NaN,NaN,NaN
33,decode_1cNxM/480/2430,207,3.375070,3.375020,ms,NaN,NaN,NaN,NaN,NaN
34,decode_1cNxM/720/1620,210,3.321020,3.320830,ms,NaN,NaN,NaN,NaN,NaN
35,decode_1cNxM/810/1440,211,3.355150,3.354980,ms,NaN,NaN,NaN,NaN,NaN
36,decode_1cNxM/1080/1080,210,3.321370,3.321310,ms,NaN,NaN,NaN,NaN,NaN
37,decode_1cNxM/1440/810,209,3.344070,3.343960,ms,NaN,NaN,NaN,NaN,NaN
38,decode_1cNxM/1620/720,210,3.330280,3.330180,ms,NaN,NaN,NaN,NaN,NaN
39,decode_1cNxM/2430/480,208,3.371070,3.370940,ms,NaN,NaN,NaN,NaN,NaN
40,decode_1cNxM/3240/360,211,3.333260,3.333200,ms,NaN,NaN,NaN,NaN,NaN
41,decode_1cNxM/4860/240,207,3.392810,3.392700,ms,NaN,NaN,NaN,NaN,NaN